services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - registry
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/homelab.crt:/etc/ssl/certs/homelab.crt
      - /etc/ssl/private/homelab.key:/etc/ssl/private/homelab.key
      - /etc/nginx/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd

  registry:
    image: registry:3
    restart: always
    volumes:
      - /var/lib/registry:/var/lib/registry

